export const STREETADDRESSES = [
  "Tallkronans väg",
  "Björklidsgatan",
  "Blåbärsstigen",
  "Solgläntans allé",
  "Vintergrönavägen",
  "Baronsgatan",
  "Hertigdömets allé",
  "Vingspirsgränd",
  "Riddarstigens väg",
  "Drottningelundsvägen",
  "Månhavets boulevard",
  "Stjärnstoftsvägen",
  "Draknästets allé",
  "Skymningsvägens sluttning",
  "Sagostigens gata",
  "Industrivägen",
  "Betonggränd",
  "Neonljusets allé",
  "Asfaltsbacken",
  "Skraptornsgatan",
  "Lillängens gränd",
  "Torparstigens väg",
  "Bagerigatan",
  "Kvarndammens väg",
  "Kyrkbackens allé",
] as const;
