export const ORGANIZATIONNAMES = [
  "Nordisk Teknik & Innovation",
  "SkogsBlomma Design",
  "Vättern Energi & Miljö",
  "Glimt IT-Konsulter",
  "Norrsken Logistics",
  "Blå Horisont Arkitektur",
  "Silverbjörn Förlag",
  "Hjärnvik Data Solutions",
  "Fyrklöverns Produkter",
  "Solstad Bygg & Projekt",
  "Krona Kreativ Produktion",
  "Midnattssol Reklam & Media",
  "Sötvatten Marin Service",
  "Ekoborg Konsult & Rådgivning",
  "Granit & Glas Interiör",
  "Ljuspunkt Ljud & Ljus",
  "Vindrosen Energi",
  "Havsbris Transporter",
  "Stjärnvägen Event & Eventyr",
  "Älvstrand Fastighetsutveckling",
] as const;
