export const PROFESSIONS = [
  "Fastighetsmäklare",
  "Fastighetsförvaltare",
  "Övriga servicearbetare",
  "Vaktmästare",
  "Reklamutdelare och tidningsdistributörer",
  "Renhållnings- och återvinningsarbetare",
  "Torg- och marknadsförsäljare",
  "Kafé- och konditoribiträden",
  "Restaurang- och köksbiträden",
  "Pizzabagare",
  "Ramppersonal, flyttkarlar och varupåfyllare",
  "Hamnarbetare",
  "Handpaketerare och andra fabriksarbetare",
  "Grovarbetare inom bygg och anläggning",
  "Bärplockare och plantörer",
  "Bilrekonditionerare, fönsterputsare",
  "Övrig hemservicepersonal",
  "Barnskötare",
  "Städare",
  "Matroser och jungmän",
  "Truckförare",
  "Kranförare",
  "Anläggningsmaskinförare",
  "Förare av jordbruks- och skogsmaskiner",
  "Lastbilsförare",
  "Buss- och spårvagnsförare",
  "Taxiförare",
  "Övriga bil-, motorcykel- och cykelförare",
  "Bangårdspersonal",
  "Lokförare",
  "Fordonsmontörer",
  "Montörer, elektrisk och elektronisk utrustning",
  "Montörer, metall-, gummi- och plastprodukter",
  "Montörer, träprodukter",
  "Övriga montörer",
  "Drifttekniker vid värme- och vattenverk",
  "Processövervakare, kemisk industri",
  "Processövervakare, metallproduktion",
  "Övriga drifttekniker och processövervakare",
  "Maskinoperatörer, påfyllning, packning och märkning",
  "Övriga process- och maskinoperatörer",
  "Butikssäljare, fackhandel",
  "Maskinoperatörer inom ytbehandling, trä",
  "Manuella ytbehandlare, trä",
  "Operatörer inom sågverk, hyvleri och plywood m.m.",
  "Processoperatörer, papper",
  "Processoperatörer, pappersmassa",
  "Maskinoperatörer, kött- och fiskberedningsindustri",
  "Maskinoperatörer, mejeri",
  "Maskinoperatörer, kvarn-, bageri- och konfektyrindustri",
  "Övriga maskinoperatörer, livsmedelsindustri m.m.",
  "Maskinoperatörer, blekning, färgning och tvättning",
  "Övriga maskinoperatörer, textil-, skinn- och läderindustri",
  "Maskinoperatörer, gummiindustri",
  "Maskinoperatörer, plastindustri",
  "Maskinoperatörer, pappersvaruindustri",
  "Maskinoperatörer, kemisktekniska och fotografiska produkter",
  "Maskinoperatörer, farmaceutiska produkter",
  "Övriga maskin- och processoperatörer vid stål- och metallverk",
  "Maskinoperatörer, ytbehandling",
  "Valsverksoperatörer",
  "Gruv- och stenbrottsarbetare",
  "Processoperatörer, stenkross- och malmförädling",
  "Brunnsborrare",
  "Maskinoperatörer, cement-, sten- och betongvaror",
  "Bergsprängare",
  "Stenhuggare",
  "Slaktare och styckare",
  "Bagare och konditorer",
  "Provsmakare och kvalitetsbedömare",
  "Skräddare och ateljésömmerskor",
  "Sömmare",
  "Tapetserare",
  "Läderhantverkare och skomakare",
  "Fin-, inrednings- och möbelsnickare",
  "Maskinsnickare och maskinoperatörer, träindustri",
  "Elektronikreparatörer och kommunikationselektriker",
  "Distributionselektriker",
  "Distributionselektriker",
  "Industrielektriker",
  "Industrielektriker",
  "Installations- och serviceelektriker",
  "Prepresstekniker",
  "Tryckare",
  "Bokbindare",
  "Finmekaniker",
  "Verktygsmakare",
  "Guld- och silversmeder",
  "Musikinstrumentmakare och övriga konsthantverkare",
  "Motorfordonsmekaniker och fordonsreparatörer",
  "Flygmekaniker",
  "Underhållsmekaniker och maskinreparatörer",
  "Smeder",
  "Uppfödare och skötare av lantbrukets husdjur",
  "Maskinställare och maskinoperatörer, metallarbete",
  "Slipare",
  "Gjutare",
  "Svetsare och gasskärare",
  "Byggnads- och ventilationsplåtslagare",
  "Tunnplåtslagare",
  "Stålkonstruktionsmontörer och grovplåtsslagare",
  "Målare",
  "Lackerare och industrimålare",
  "Skorstensfejare",
  "Saneringsarbetare",
  "Takmontörer",
  "Golvläggare",
  "Isoleringsmontörer",
  "Glastekniker",
  "VVS-montörer",
  "Kyl- och värmepumpstekniker",
  "Träarbetare, snickare",
  "Murare",
  "Betongarbetare",
  "Anläggningsarbetare",
  "Anläggningsdykare",
  "Ställningsbyggare",
  "Övriga byggnads- och anläggningsarbetare",
  "Fiskare",
  "Fiskodlare",
  "Skogsarbetare",
  "Växtodlare och djuruppfödare, blandad drift",
  "Uppfödare och skötare av sällskapsdjur",
  "Övriga djuruppfödare och djurskötare",
  "Odlare av jordbruksväxter, frukt och bär",
  "Trädgårdsodlare",
  "Trädgårdsanläggare",
  "Brandmän",
  "Kriminalvårdare",
  "Väktare och ordningsvakter",
  "Tandsköterskor",
  "Tandhygienister",
  "Skötare",
  "Vårdare, boendestödjare",
  "Personliga assistenter",
  "Övrig vård- och omsorgspersonal",
  "Vårdbiträden",
  "Ambulanssjukvårdare",
  "Barnsköterskor",
  "Elevassistenter",
  "Eventsäljare och butiksdemonstratörer",
  "Telefonförsäljare",
  "Kassapersonal",
  "Säljande butikschefer och avdelningschefer i butik",
  "Butikssäljare, dagligvaror",
  "Optikerassistenter",
  "Bensinstationspersonal",
  "Uthyrare",
  "Apotekstekniker",
  "Övrig servicepersonal",
  "Begravnings- och krematoriepersonal",
  "Fastighetsskötare",
  "Städledare och husfruar",
  "Frisörer",
  "Hudterapeuter",
  "Massörer och massageterapeuter",
  "Fotterapeuter",
  "Övriga skönhets- och kroppsterapeuter",
  "Terapeuter inom alternativmedicin",
  "Bartendrar",
  "Hovmästare och servitörer",
  "Kockar och kallskänkor",
  "Guider och reseledare",
  "Tågvärdar och ombordansvariga",
  "Kabinpersonal",
  "Brevbärare och postterminalarbetare",
  "Arkiv- och biblioteksassistenter",
  "Transportledare och transportsamordnare",
  "Lager- och terminalpersonal",
  "Arbetsledare inom lager och terminal",
  "Marknadsundersökare och intervjuare",
  "Kontorsreceptionister",
  "Hotellreceptionister",
  "Telefonister",
  "SOS-operatörer",
  "Övrig bevaknings- och säkerhetspersonal",
  "Kundtjänstpersonal",
  "Resesäljare och trafikassistenter",
  "Fartygsbefäl",
  "Domstols- och juristsekreterare",
  "Inkasserare och pantlånare",
  "Croupierer och oddssättare",
  "Övriga kontorsassistenter och sekreterare",
  "Medicinska sekreterare, vårdadministratörer",
  "Skolassistenter",
  "Inköps- och orderassistenter",
  "Marknads- och försäljningsassistenter",
  "Backofficepersonal",
  "Löne- och personaladministratörer",
  "Ekonomiassistenter",
  "Ljus-, ljud- och scentekniker",
  "Bild- och sändningstekniker",
  "Webbmaster och webbadministratörer",
  "Nätverks- och systemtekniker",
  "Systemadministratörer",
  "Supporttekniker, IT",
  "Drifttekniker, IT",
  "Storhushållsföreståndare",
  "Köksmästare och souschefer",
  "Övriga utbildare och instruktörer",
  "Övriga pedagoger med teoretisk specialistkompetens",
  "Piloter",
  "Trafiklärare",
  "Gruppledare för kontorspersonal",
  "Övriga förmedlare",
  "Arbetsförmedlare",
  "Evenemangs- och reseproducenter",
  "Speditörer och transportmäklare",
  "Ordersamordnare",
  "Övriga yrken inom kultur och underhållning",
  "Inspicienter och scriptor",
  "Inredare, dekoratörer och scenografer",
  "Fotografer",
  "Friskvårdskonsulenter och hälsopedagoger",
  "Fritidsledare",
  "Idrottstränare och instruktörer",
  "Professionella idrottsutövare",
  "Pastorer",
  "Behandlingsassistenter och socialpedagoger",
  "Poliser",
  "Övriga handläggare",
  "Chefssekreterare och VD-assistenter",
  "Brandingenjörer och byggnadsinspektörer",
  "Ingenjörer och tekniker inom bygg och anläggning",
  "Säkerhetsinspektörer",
  "Socialförsäkringshandläggare",
  "Skattehandläggare",
  "Tull- och kustbevakningstjänstemän",
  "Inköpare och upphandlare",
  "Företagssäljare",
  "Försäkringssäljare och försäkringsrådgivare",
  "Skadereglerare och värderare",
  "Redovisningsekonomer",
  "Arbetsledare inom bygg, anläggning och gruva",
  "Ingenjörer och tekniker inom maskinteknik",
  "Banktjänstemän",
  "Mäklare inom finans",
  "Djursjukskötare",
  "Laboratorieingenjörer",
  "Tekniker, bilddiagnostik och medicinteknisk utrustning",
  "Biomedicinska analytiker",
  "Receptarier",
  "Tandtekniker och ortopedingenjörer",
  "Flygtekniker",
  "Flygledare",
  "Maskinbefäl",
  "Arbetsledare inom tillverkning",
  "Övriga ingenjörer och tekniker",
  "GIS- och kartingenjörer",
  "Ingenjörer och tekniker inom gruvteknik och metallurgi",
  "Ingenjörer och tekniker inom kemi och kemiteknik",
  "Ingenjörer och tekniker inom elektroteknik",
  "Ingenjörer och tekniker inom industri, logistik och produktionsplanering",
  "Övriga yrken inom socialt arbete",
  "Biståndsbedömare",
  "Kuratorer",
  "Socialsekreterare",
  "Diakoner",
  "Präster",
  "Skådespelare",
  "Regissörer och producenter av film, teater m.m.",
  "Koreografer och dansare",
  "Musiker, sångare och kompositörer",
  "Bildkonstnärer",
  "Översättare, tolkar och lingvister",
  "Journalister",
  "Författare",
  "Arkeologer och specialister inom humaniora m.m.",
  "Bibliotekarier och arkivarier",
  "Museiintendenter",
  "Övriga jurister",
  "Förvaltnings- och organisationsjurister",
  "Affärs- och företagsjurister",
  "Åklagare",
  "Domare",
  "Advokater",
  "Övriga IT-specialister",
  "IT-säkerhetsspecialister",
  "Systemförvaltare",
  "Systemtestare och testledare",
  "Utvecklare inom spel och digitala media",
  "Mjukvaru- och systemutvecklare",
  "Systemanalytiker och IT-arkitekter",
  "Informatörer, kommunikatörer och PR-specialister",
  "Marknadsanalytiker och marknadsförare",
  "Personal- och HR-specialister",
  "Studie- och yrkesvägledare",
  "Speciallärare och specialpedagoger",
  "Planerare och utredare",
  "Lednings- och organisationsutvecklare",
  "Övriga ekonomer",
  "Nationalekonomer och makroanalytiker",
  "Traders och fondförvaltare",
  "Finansanalytiker och investeringsrådgivare",
  "Controller",
  "Revisorer",
  "Förskollärare",
  "Fritidspedagoger",
  "Grundskollärare",
  "Gymnasielärare",
  "Lärare i yrkesämnen",
  "Övriga universitets- och högskolelärare",
  "Doktorander",
  "Forskarassistenter",
  "Universitets- och högskolelektorer",
  "Professorer",
  "Övriga specialister inom hälso- och sjukvård",
  "Optiker",
  "Audionomer och logopeder",
  "Dietister",
  "Apotekare",
  "Arbetsterapeuter",
  "Fysioterapeuter och sjukgymnaster",
  "Kiropraktorer och naprapater",
  "Tandläkare",
  "Veterinärer",
  "Psykoterapeuter",
  "Psykologer",
  "Övriga specialistsjuksköterskor",
  "Röntgensjuksköterskor",
  "Företagssköterskor",
  "Skolsköterskor",
  "Barnsjuksköterskor",
  "Operationssjuksköterskor",
  "Intensivvårdssjuksköterskor",
  "Geriatriksjuksköterskor",
  "Ambulanssjuksköterskor",
  "Psykiatrisjuksköterskor",
  "Distriktssköterskor",
  "Anestesisjuksköterskor",
  "Barnmorskor",
  "Grundutbildade sjuksköterskor",
  "Övriga läkare",
  "AT-läkare",
  "ST-läkare",
  "Specialistläkare",
  "Arbetsmiljöingenjörer, yrkes- och miljöhygieniker",
  "Miljö- och hälsoskyddsinspektörer",
  "Specialister inom miljöskydd och miljöteknik",
  "Övriga designer och formgivare",
  "Designer inom spel och digitala medier",
  "Grafiska formgivare",
  "Industridesigner",
  "Lantmätare",
  "Planeringsarkitekter",
  "Landskapsarkitekter",
  "Arkitekter",
  "Civilingenjörsyrken inom logistik och produktionsplanering",
  "Civilingenjörsyrken inom bygg och anläggning",
  "Civilingenjörsyrken inom elektroteknik",
  "Civilingenjörsyrken inom maskinteknik",
  "Civilingenjörsyrken inom kemi och kemiteknik",
  "Civilingenjörsyrken inom gruvteknik och metallurgi",
  "Övriga civilingenjörsyrken",
  "Specialister och rådgivare inom skogsbruk",
  "Specialister och rådgivare inom lantbruk m.m.",
  "Farmakologer och biomedicinare",
  "Växt- och djurbiologer",
  "Cell- och molekylärbiologer",
  "Statistiker",
  "Matematiker och aktuarier",
  "Geologer och geofysiker",
  "Kemister",
  "Meteorologer",
  "Fysiker och astronomer",
  "Övriga chefer inom övrig servicenäring",
  "Chefer inom friskvård, sport och fritid",
  "Chefer inom handel",
  "Restaurang- och kökschefer",
  "Hotell- och konferenschefer",
  "Chefer inom bank, finans och försäkring",
  "Övriga chefer inom samhällsservice",
  "Chefer och ledare inom trossamfund",
  "Chefer inom äldreomsorg",
  "Chefer inom socialt och kurativt arbete",
  "Chefer inom hälso- och sjukvård",
  "Övriga chefer inom utbildning",
  "Chefer inom grund- och gymnasieskola samt vuxenutbildning",
  "Chefer inom förskoleverksamhet",
  "Förvaltare inom skogsbruk och lantbruk",
  "Produktionschefer inom tillverkning",
  "Driftchefer inom bygg, anläggning och gruva",
  "Fastighets- och förvaltningschefer",
  "Chefer inom arkitekt- och ingenjörsverksamhet",
  "Forsknings- och utvecklingschefer",
  "Inköps-, logistik- och transportchefer",
  "IT-chefer",
  "Övriga administrations- och servicechefer",
  "Försäljnings- och marknadschefer",
  "Informations-, kommunikations- och PR-chefer",
  "Förvaltnings- och planeringschefer",
  "Personal- och HR-chefer",
  "Ekonomi- och finanschefer",
  "Verkställande direktörer",
  "Politiker",
  "General-, landstings- och kommundirektörer",
  "Chefstjänstemän i intresseorganisationer",
  "Officerare",
  "Specialistofficerare",
  "Soldater",
  "Undersköterskor, hemtjänst, hemsjukvård, äldreboende och habilitering",
  "Undersköterskor, vård- och specialavdelning och mottagning",
  "Officerare",
  "Politiker och högre ämbetsmän",
  "Verkställande direktörer",
  "Ekonomi- och finanschefer",
  "Personal- och HR-chefer",
  "Förvaltnings- och planeringschefer",
  "IT-chefer",
  "Fysiker, kemister",
  "Matematiker, aktuarier och statistiker",
  "Biologer, farmakologer och specialister inom lant- och skogsbruk",
  "Civilingenjörsyrken",
  "Läkare",
  "Sjuksköterskor",
  "Sjuksköterskor (fortsättning)",
  "Universitets- och högskolelärare",
  "Lärare i yrkesämnen",
  "Gymnasielärare",
  "Grundskollärare, fritidspedagoger och förskollärare",
  "Andra pedagoger med teoretisk specialistkompetens",
  "Revisorer, finansanalytiker och fondförvaltare",
  "Organisationsutvecklare, utredare och HR-specialister",
  "Marknadsförare och informatörer",
  "Ingenjörer och tekniker",
  "Arbetsledare inom bygg och tillverkning m.m.",
  "Piloter, fartygs- och maskinbefäl",
  "Köksmästare och souschefer",
  "Kabinpersonal, tågmästare och guider",
  "Resesäljare, kundtjänstpersonal och receptionister",
  "Croupierer och inkasserare",
  "Kontorsassistenter och sekreterare",
  "Trafiklärare och instruktörer",
  "Fotografer, dekoratörer och underhållningsartister",
  "Idrottsutövare och fritidsledare",
  "Behandlingsassistenter och pastorer",
  "Försäkringsrådgivare, företagssäljare och inköpare",
  "Banktjänstemän och redovisningsekonomer",
  "Djursjukskötare och veterinärassistenter",
  "Terapeuter inom alternativmedicin",
  "Biomedicinska analytiker, tandtekniker och laboratorieingenjörer",
  "Skönhets- och kroppsterapeuter",
  "Bil-, motorcykel- och cykelförare",
  "Kockar och kallskänkor",
  "Maskinoperatörer, livsmedelsindustri",
  "Processoperatörer, trä- och pappersindustri",
  "Montörer",
  "Maskinoperatörer, gummi-, plast- och pappersvaruindustri",
  "Lokförare och bangårdspersonal",
  "Maskinoperatörer, kemiska och farmaceutiska produkter m.m.",
  "Städare och hemservicepersonal",
  "Tvättare, fönsterputsare och övriga rengöringsarbetare",
  "Gjutare, svetsare och plåtslagare",
  "Malmförädlingsyrken och brunnsborrare",
  "Elektronikreparatörer och kommunikationselektriker",
  "Installations- och industrielektriker",
  "Prepresstekniker, tryckare och bokbindare",
  "Finmekaniker och konsthantverkare",
  "Process- och maskinoperatörer, vid stål- och metallverk",
  "Smeder och verktygsmakare",
  "Hovmästare, servitörer och bartendrar",
  "Målare, lackerare och skorstensfejare",
  "Snickare, murare och anläggningsarbetare",
  "Växtodlare och djuruppfödare, blandad drift",
  "Djuruppfödare och djurskötare",
  "Växtodlare inom jordbruk och trädgård",
  "Butikspersonal",
  "Städledare och fastighetsskötare",
  "Fordonsmekaniker och reparatörer",
  "Hamnarbetare och ramppersonal",
  "Handpaketerare och andra fabriksarbetare",
  "Grovarbetare inom bygg och anläggning",
  "Bärplockare och plantörer",
  "Takmontörer, golvläggare och VVS-montörer",
  "Maskinoperatörer, textil-, tvätt- och läderindustri m.m.",
  "Specialistofficerare",
  "Soldater",
  "Snabbmatspersonal, köks- och restaurangbiträden",
  "Torg- och marknadsförsäljare",
  "Återvinningsarbetare",
  "Tidningsdistributörer, vaktmästare och övriga servicearbetare",
  "Andra process- och maskinoperatörer",
  "Drifttekniker och processövervakare",
  "Lastbils- och bussförare",
  "Maskinförare",
  "Matroser och jungmän",
  "Ytbehandlare, trä och möbelsnickare",
  "Skräddare, tapetserare och läderhantverkare",
  "Slaktare, bagare och livsmedelsförädlare",
  "Skogsarbetare",
  "Fiskodlare och fiskare",
  "Övrig servicepersonal",
  "Kassapersonal",
  "Eventsäljare och telefonförsäljare",
  "Barnskötare och elevassistenter",
  "Undersköterskor",
  "Vårdbiträden",
  "Skötare, vårdare och personliga assistenter",
  "Tandsköterskor",
  "Andra bevaknings- och säkerhetsyrken",
  "Lagerpersonal och transportledare",
  "Arkiv- och biblioteksassistenter",
  "Brevbärare och postterminalarbetare",
  "Tandhygienister",
  "Förmedlare",
  "Juristsekreterare, chefssekreterare och institutionssekreterare",
  "Skatte- och socialförsäkringshandläggare",
  "Poliser",
  "Drift-, support- och nätverkstekniker",
  "Bild-, ljud- och ljustekniker",
  "Arkitekter och lantmätare",
  "Designer och formgivare",
  "Specialister inom miljö- och hälsoskydd",
  "Psykologer och psykoterapeuter",
  "Veterinärer",
  "Tandläkare",
  "Naprapater, sjukgymnaster och arbetsterapeuter",
  "Andra specialister inom hälso- och sjukvård",
  "IT-arkitekter, systemutvecklare och testledare",
  "Jurister",
  "Museiintendenter och bibliotekarier",
  "Författare, journalister och tolkar",
  "Konstnärer, musiker och skådespelare",
  "Socialsekreterare och kuratorer",
  "Präster och diakoner",
  "Informations-, kommunikations- och PR-chefer",
  "Försäljnings- och marknadschefer",
  "Övriga administrations- och servicechefer",
  "Inköps-, logistik- och transportchefer",
  "Forsknings- och utvecklingschefer",
  "Chefer inom arkitekt- och ingenjörsverksamhet",
  "Fastighets- och förvaltningschefer",
  "Driftchefer inom bygg, anläggning och gruva",
  "Produktionschefer inom tillverkning",
  "Förvaltare inom skogsbruk och lantbruk",
  "Chefer inom grund- och gymnasieskola samt vuxenutbildning",
  "Chefer inom förskoleverksamhet",
  "Övriga chefer inom utbildning",
  "Chefer inom hälso- och sjukvård",
  "Chefer inom socialt och kurativt arbete",
  "Chefer inom äldreomsorg",
  "Chefer och ledare inom trossamfund",
  "Övriga chefer inom samhällsservice",
  "Chefer inom bank, finans och försäkring",
  "Hotell- och konferenschefer",
  "Restaurang- och kökschefer",
  "Chefer inom handel",
  "Chefer inom friskvård, sport och fritid",
  "Övriga chefer inom övrig servicenäring",
  "Officerare",
  "Politiker, verkställande direktörer och högre ämbetsmän",
  "Chefer inom ekonomi, HR, marknadsföring och försäljning samt annan administration m.m.",
  "Chefer inom IT, logistik, FoU, fastighetsbolag, bygg- och ingenjörsverksamhet samt tillverkning m.m.",
  "Yrken med krav på fördjupad högskolekompetens inom naturvetenskap och teknik",
  "Yrken med krav på fördjupad högskolekompetens inom hälso- och sjukvård",
  "Yrken med krav på fördjupad högskolekompetens inom utbildning",
  "Yrken med krav på fördjupad högskolekompetens inom ekonomi och förvaltning",
  "Yrken med krav på högskolekompetens eller motsvarande inom teknik",
  "Yrken med krav på högskolekompetens eller motsvarande inom hälso- och sjukvård samt laboratorium",
  "Yrken med krav på högskolekompetens eller motsvarande inom ekonomi och förvaltning",
  "Yrken med krav på högskolekompetens eller motsvarande inom kultur, friskvård och socialt arbete m.m.",
  "Kontorsassistenter och sekreterare",
  "Kundserviceyrken",
  "Serviceyrken",
  "Försäljningsyrken inom detaljhandeln m.m.",
  "Lantbruks- och trädgårdsyrken",
  "Byggnads- och anläggningsyrken",
  "Metallhantverks- och reparatörsyrken",
  "Finmekaniska, grafiska och konsthantverksyrken",
  "Installations- och serviceyrken inom el och elektronik",
  "Process- och maskinoperatörer",
  "Montörer",
  "Städyrken",
  "Bärplockare och plantörer",
  "Andra yrken inom bygg, tillverkning och godshantering",
  "Transport- och maskinföraryrken",
  "Specialistofficerare",
  "Soldater",
  "Snabbmatspersonal, köks- och restaurangbiträden",
  "Torg- och marknadsförsäljare",
  "Återvinningsarbetare, tidningsdistributörer och övriga servicearbetare",
  "Hantverksyrken inom trä, textil m.m.",
  "Livsmedelsförädlare",
  "Skogsarbetare, fiskodlare och fiskare",
  "Omsorgsyrken",
  "Andra bevaknings- och säkerhetsyrken",
  "Yrken inom materialförvaltning m.m.",
  "Andra kontors- och kundserviceyrken",
  "Yrken med krav på högskolekompetens eller motsvarande inom IT, ljud- och ljusteknik m.m.",
  "Yrken med krav på fördjupad högskolekompetens inom IT",
  "Yrken med krav på fördjupad högskolekompetens inom juridik, kultur och socialt arbete m.m.",
  "Chefer inom utbildning",
  "Chefer inom hälso- och sjukvård samt annan samhällsservice",
  "Chefer inom bank, finans och försäkring",
  "Chefer inom övrig servicenäring",
  "Militära yrken",
  "Chefsyrken",
  "Yrken med krav på fördjupad högskolekompetens",
  "Yrken med krav på högskolekompetens eller motsvarande",
  "Yrken inom administration och kundtjänst",
  "Service-, omsorgs- och försäljningsyrken",
  "Yrken inom lantbruk, trädgård, skogsbruk och fiske",
  "Yrken inom byggverksamhet och tillverkning",
  "Yrken inom maskinell tillverkning och transport m.m.",
  "Yrken med krav på kortare utbildning eller introduktion",
] as const;
